on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: abhaydeshpande
          POSTGRES_USER: abhaydeshpande
          POSTGRES_DB: abhaydeshpande
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries
        ports:
          - 5432:5432
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node createTable.js
      - run: node insertTable.js
      - run: sleep 30
      - run: docker logs postgres
      - run: node server.js
      - run: docker logs postgres
